# Use an official Python runtime as a parent image
FROM python:3.9-bookworm
# FROM python:3.9-slim

LABEL Description="ReviveMed Linux environment for matt training code"
LABEL tags="matt_training_models"

# Set the working directory in the container
WORKDIR /app

# the more secure method
# ARG BITBUCKET_ACCESS_KEY

# less secure
# ENV BITBUCKET_ACCESS_KEY=your_access_key


# Copy the current directory contents into the container at /app
# COPY . /app
# only copy the requirements_4.txt file
COPY requirements.txt .

RUN apt-get update

# install git
RUN apt-get install -y git
# Install useful system packages
RUN apt-get install -y screen htop
RUN apt-get install -y build-essential
RUN apt-get install -y pkg-config
RUN apt-get install -y libmariadb-dev-compat
RUN apt-get update && apt-get install -y vim
RUN apt-get install -y r-base

RUN pip install --upgrade pip
RUN pip install mysqlclient
RUN pip install torch


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080
EXPOSE 8888

# Define environment variable
ENV NAME World